### ISSUE TITLE
The journal

### ISSUE THREAD

**Issue by S00lis** [Araraura/HallowScribe#2]
The collecter is not in the journal.
Please fix soon. Thank you.

Sincerely, some guy.

**Comment by Araraura** [comment]
> The collecter is not in the journal. Please fix soon. Thank you.
> 
> Sincerely, some guy.

It seems that if you're looking up "collector" instead of "the collector", the entry won't appear.

![image](https://github.com/Araraura/HallowScribe/assets/25017422/3ed912df-360b-4a90-a9d5-fcabb6c0e08e)
![image](https://github.com/Araraura/HallowScribe/assets/25017422/4fd083f9-1378-4061-b763-0e5461054ebf)

I think changing `.startsWith` with `.includes` in the filtering code should fix the issue.
